project:
  type: book
  output-dir: _book

book:
  title: "Programación R para economistas"
  description: "Libro de R."
  author:
    - name: Edison Achalma Mendoza  # Nombre del autor
      url: https://achalmaedison.netlify.app  # URL del autor
      affiliation: Universidad Nacional de San Cristóbal de Huamanga  # Afiliación del autor
      affiliation-url: https://www.gob.pe/unsch  # URL de la afiliación del autor
      orcid: 0000-0001-6996-3364  # ORCID del autor
  date: "06/11/2023"
  search: true
  repo-url: https://github.com/achalmed/R
  repo-branch: main
  repo-actions: [edit, issue, source]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  cover-image: cover.png
  cover-image-alt: |
   Alternative text describing the book cover 
   
  page-footer:
    left: |
      Programación R para economistas (1e) fue escrito por Edison Achalma.
    right:
      - icon: twitter
        href: https://twitter.com/achalmaedison
        aria-label: Quarto Twitter
      - icon: github
        href: https://github.com/achalmed/website-achalma
        aria-label: Quarto GitHub 
      
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    
    - part: Capitulo 1
      chapters:
        - 1-instalacion-r/index.qmd
        - 2-que-ofrece-r/index.qmd
        - 3-debemos-saber-r/index.qmd
        - 4-manipulacion-datos-r/index.qmd
        
    - references.qmd
    
  appendices:
    - apendice.qmd

  page-navigation: true
    
comments:
  hypothesis: true
  
bibliography: references.bib
citation: true  # Habilitar citas bibliográficas
google-scholar: true  # Habilitar enlaces a Google Scholar
csl: apa-6th-edition.csl  # Estilo de citas
cite-method: biblatex  # Método de citación

links-as-notes: true
lang: es 
crossref:
  fig-title: Figura    # (default is "Figure")
  tbl-title: Tabla     # (default is "Table")
  title-delim: —       # (default is ":")
  fig-prefix: figura   # (default is "Figure")
  tbl-prefix: tabla    # (default is "Table")
  ref-hyperlink: false # (default is true)
execute:
  eval: true
  # keep-ipynb: true
  keep-md: true  # Mantener archivos .md generados
  echo: true  # Mostrar comandos ejecutados
  output: true  # Mostrar resultados de la ejecución
  warning: false  # Ocultar advertencias
  error: false  # Ocultar errores
  cache: true  # Habilitar el almacenamiento en caché
  enabled: false  # Deshabilitar la ejecución

highlight-style: github  # Estilo de resaltado de código

format:
  pdf:
    documentclass: scrartcl  # Clase de documento para el PDF
    # papersize: letter  # Tamaño del papel
    language: es  # Idioma del documento
    # geometry: 
    #   - top=2.54cm  # Margen superior
    #   - right=2.54cm  # Margen derecho
    #   - bottom=2.54cm  # Margen inferior
    #   - left=2.54cm  # Margen izquierdo
    # toc: true  # Habilitar la tabla de contenido
    # toc-depth: 3  # Profundidad de la tabla de contenido
    # toc-title: Contenidos  # Título de la tabla de contenido
    # number-sections: true  # Numerar secciones
    # number-depth: 3  # Profundidad de numeración de secciones
    colorlinks: true  # Habilitar enlaces con colores
    link-citation: true  # Habilitar enlaces en las citas
    link-bibliography: true  # Habilitar enlaces en la bibliografía
    keep-tex: true  # Mantener archivos .tex generados
    pdf-engine: pdflatex  # Motor de PDF
    include-in-header: 
      - file: preamble.tex  # Archivo LaTeX a incluir en el encabezado
  html:
    theme: cosmo
    toc: true  # Mostrar tabla de contenidos
    toc-depth: 3  # Profundidad de la tabla de contenidos
    toc-expand: 2  # Nivel de anidamiento inicial de la tabla de contenidos expandida
    toc-title: Contenidos  # Título de la tabla de contenidos
    toc-location: right  # Ubicación de la tabla de contenidos (left, right)
    # number-sections: true  # Numerar las secciones del documento
    # number-depth: 3  # Profundidad de numeración de secciones
    smooth-scroll: true  # Activar desplazamiento suave en el formato HTML
    # link-external-icon: true  # Mostrar icono para enlaces externos
    link-external-newwindow: true  # Abrir enlaces externos en una nueva ventana
    citations-hover: true  # Mostrar citas emergentes al pasar el cursor sobre ellas
    footnotes-hover: true  # Mostrar notas al pie emergentes al pasar el cursor sobre ellas
    code-copy: true  # Habilitar la funcionalidad de copiar código
    code-fold: false  # Habilitar el plegado de código
    code-summary: "Mostrar el código"  # Texto para mostrar/ocultar el código
    code-overflow: wrap  # Manejo de desbordamiento de código (wrap, scroll, truncate, etc.)
    code-tools:
      source: true  # Mostrar el código fuente en las herramientas de código
      toggle: false  # Habilitar la funcionalidad de alternar código
      caption: none  # Opción para la leyenda del código

editor: visual